[package]
name = "oxcart"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
bumpalo = "3.12.0"
copy_arena = "0.1.1"
expect-test = "1.4.0"
slotmap = "1.0.6"
typed-arena = "2.0.2"
generational-arena = "0.2.8"
