pub(crate) extern crate alloc;
pub(crate) use core::alloc::Layout;
pub(crate) use core::cmp::max;
pub(crate) use core::convert::Infallible;
pub(crate) use core::marker::PhantomData;
pub(crate) use core::mem::MaybeUninit;
pub(crate) use core::mem::align_of;
pub(crate) use core::mem::needs_drop;
pub(crate) use core::mem::size_of;
pub(crate) use core::ptr::NonNull;
pub(crate) use core::ptr::null_mut;
pub(crate) use core::slice;
